/**
 * Persistence contract for a Fintoc payment before its reservation exists.
 * A row is created against a hold (`holdId`) when the checkout session is
 * created; once Fintoc reports the payment as approved, the same row is
 * updated in place with `reservationId` set (see
 * `ReservationRepository.createConfirmedPayNowReservation` in
 * `@/features/reservations`) rather than replaced.
 */
export type FintocPaymentStatus =
  | "pending"
  | "approved"
  | "rejected"
  | "cancelled"
  | "refunded"
  | "requires_action";

export type FintocPaymentRecord = Readonly<{
  amountClp: number;
  currency: "CLP";
  externalReference: string;
  holdId: string | null;
  id: string;
  provider: "fintoc";
  providerPaymentId: string | null;
  refundedAmountClp: number;
  reservationId: string | null;
  status: FintocPaymentStatus;
}>;

export type CreatePendingFintocPaymentInput = Readonly<{
  /**
   * Generated by the caller (`crypto.randomUUID()`) rather than left to the
   * database default, so it is known before the Fintoc API call and can be
   * embedded in `success_url`/`cancel_url` as the token the post-redirect
   * status page polls by — unlike `holdId`, this id survives the hold being
   * deleted once the payment is confirmed or fails (see
   * `initiateFintocCheckout` and `app/reservar/procesando/page.tsx`).
   */
  id: string;
  amountClp: number;
  externalReference: string;
  holdId: string;
}>;

export type FintocPaymentRepository = Readonly<{
  /** Plain, non-transactional insert: creating a payment row does not change room occupancy. */
  createPendingPayment: (
    input: CreatePendingFintocPaymentInput
  ) => Promise<FintocPaymentRecord>;
  getPaymentByExternalReference: (
    externalReference: string
  ) => Promise<FintocPaymentRecord | null>;
  /** Correlates a standalone `payment_intent.*` webhook event, which carries no checkout-session reference (see `fintoc-webhook.ts`). */
  getPaymentByProviderPaymentId: (
    providerPaymentId: string
  ) => Promise<FintocPaymentRecord | null>;
  /** Used by the admin panel to find the Fintoc payment of a confirmed `pay_now` reservation, e.g. to offer a refund. */
  getPaymentByReservationId: (
    reservationId: string
  ) => Promise<FintocPaymentRecord | null>;
  getPaymentById: (id: string) => Promise<FintocPaymentRecord | null>;
  /**
   * Reflects a payment that `ReservationRepository.createConfirmedPayNowReservation`
   * already approved (in Postgres, the very same row) so this repository's
   * own read model (`getPaymentByExternalReference`) does not keep
   * reporting it as `pending`/`requires_action` — otherwise a later
   * redelivered webhook event would look up a stale, non-final payment.
   */
  markApproved: (
    payment: FintocPaymentRecord,
    input: Readonly<{ providerPaymentId: string; reservationId: string }>
  ) => Promise<FintocPaymentRecord>;
  /** Sent when Fintoc reports the payment needs a further customer/counterparty action; the hold stays intact. */
  markRequiresAction: (
    payment: FintocPaymentRecord,
    providerPaymentId: string
  ) => Promise<FintocPaymentRecord>;
  /**
   * Marks a payment definitively `rejected`/`cancelled`. Does not touch the
   * hold: callers release it separately (see `releaseFailedPayNowHold` in
   * `@/features/reservations/confirm-pay-now-reservation.ts`) since a hold
   * may already be gone by the time this runs.
   */
  markFailed: (
    payment: FintocPaymentRecord,
    status: "rejected" | "cancelled",
    providerPaymentId?: string
  ) => Promise<FintocPaymentRecord>;
  /**
   * Adds `refundAmountClp` to the running total. Only flips `status` to
   * `refunded` once the cumulative refunded amount reaches `amountClp`;
   * a partial refund leaves `status` at `approved` (see
   * `fintoc-payment-integration` spec, "Reembolso de pagos Fintoc").
   */
  applyRefund: (
    payment: FintocPaymentRecord,
    refundAmountClp: number
  ) => Promise<FintocPaymentRecord>;
  /**
   * Records a webhook event id for idempotency. Returns `alreadyProcessed:
   * true` without any side effect if the same `(provider, providerEventId)`
   * pair was already recorded (see `payment_events_provider_event_unique`).
   *
   * Call this only once processing has actually succeeded, or call
   * `discardWebhookEvent` if processing then fails — recording it first and
   * leaving it recorded on failure would make a transient error permanently
   * swallow every one of Fintoc's retries for that event (see
   * `app/api/webhooks/fintoc/route.ts`).
   */
  recordWebhookEvent: (
    input: Readonly<{
      eventType: string;
      occurredAt: Date;
      payload: unknown;
      paymentId: string | null;
      providerEventId: string;
    }>
  ) => Promise<Readonly<{ alreadyProcessed: boolean }>>;
  /** Reverts a `recordWebhookEvent` call so a genuinely failed event can be retried by Fintoc. */
  discardWebhookEvent: (providerEventId: string) => Promise<void>;
}>;

function assertNotAlreadyFinal(payment: FintocPaymentRecord) {
  if (payment.status !== "pending" && payment.status !== "requires_action") {
    throw new Error(
      `Fintoc payment ${payment.id} is already in a final state: ${payment.status}`
    );
  }
}

type MockFintocPaymentStorage = Readonly<{
  paymentsById: Map<string, FintocPaymentRecord>;
  paymentsByExternalReference: Map<string, string>;
  processedEventIds: Set<string>;
}>;

const canonicalFintocPaymentStorageKey = Symbol.for(
  "vista-valle.mock.canonical-fintoc-payment-storage"
);

function createFintocPaymentStorage(): MockFintocPaymentStorage {
  return {
    paymentsById: new Map(),
    paymentsByExternalReference: new Map(),
    processedEventIds: new Set(),
  };
}

function getCanonicalFintocPaymentStorage(): MockFintocPaymentStorage {
  const scope = globalThis as typeof globalThis & {
    [canonicalFintocPaymentStorageKey]?: MockFintocPaymentStorage;
  };
  return (scope[canonicalFintocPaymentStorageKey] ??=
    createFintocPaymentStorage());
}

/** In-memory double used only by the explicit mock context (design.md decision 13). */
export function createMockFintocPaymentRepository(
  storage: MockFintocPaymentStorage = createFintocPaymentStorage()
): FintocPaymentRepository {
  return Object.freeze({
    createPendingPayment: async (input) => {
      const payment: FintocPaymentRecord = Object.freeze({
        amountClp: input.amountClp,
        currency: "CLP",
        externalReference: input.externalReference,
        holdId: input.holdId,
        id: input.id,
        provider: "fintoc",
        providerPaymentId: null,
        refundedAmountClp: 0,
        reservationId: null,
        status: "pending",
      });
      storage.paymentsById.set(payment.id, payment);
      storage.paymentsByExternalReference.set(
        payment.externalReference,
        payment.id
      );
      return payment;
    },
    getPaymentByExternalReference: async (externalReference) => {
      const id = storage.paymentsByExternalReference.get(externalReference);
      return id ? (storage.paymentsById.get(id) ?? null) : null;
    },
    getPaymentByProviderPaymentId: async (providerPaymentId) =>
      [...storage.paymentsById.values()].find(
        (payment) => payment.providerPaymentId === providerPaymentId
      ) ?? null,
    getPaymentByReservationId: async (reservationId) =>
      [...storage.paymentsById.values()].find(
        (payment) => payment.reservationId === reservationId
      ) ?? null,
    getPaymentById: async (id) => storage.paymentsById.get(id) ?? null,
    markApproved: async (payment, input) => {
      const updated = Object.freeze({
        ...payment,
        providerPaymentId: input.providerPaymentId,
        reservationId: input.reservationId,
        status: "approved" as const,
      });
      storage.paymentsById.set(updated.id, updated);
      return updated;
    },
    markRequiresAction: async (payment, providerPaymentId) => {
      assertNotAlreadyFinal(payment);
      const updated = Object.freeze({
        ...payment,
        providerPaymentId,
        status: "requires_action" as const,
      });
      storage.paymentsById.set(updated.id, updated);
      return updated;
    },
    markFailed: async (payment, status, providerPaymentId) => {
      assertNotAlreadyFinal(payment);
      const updated = Object.freeze({
        ...payment,
        providerPaymentId: providerPaymentId ?? payment.providerPaymentId,
        status,
      });
      storage.paymentsById.set(updated.id, updated);
      return updated;
    },
    applyRefund: async (payment, refundAmountClp) => {
      if (payment.status !== "approved") {
        throw new Error(
          `Fintoc payment ${payment.id} is not approved and cannot be refunded`
        );
      }
      if (refundAmountClp <= 0) {
        throw new Error("Refund amount must be positive");
      }
      const refundedAmountClp = payment.refundedAmountClp + refundAmountClp;
      if (refundedAmountClp > payment.amountClp) {
        throw new Error("Refund amount exceeds the payment total");
      }
      const updated = Object.freeze({
        ...payment,
        refundedAmountClp,
        status:
          refundedAmountClp === payment.amountClp
            ? ("refunded" as const)
            : payment.status,
      });
      storage.paymentsById.set(updated.id, updated);
      return updated;
    },
    recordWebhookEvent: async (input) => {
      const key = `fintoc:${input.providerEventId}`;
      if (storage.processedEventIds.has(key)) {
        return Object.freeze({ alreadyProcessed: true });
      }
      storage.processedEventIds.add(key);
      return Object.freeze({ alreadyProcessed: false });
    },
    discardWebhookEvent: async (providerEventId) => {
      storage.processedEventIds.delete(`fintoc:${providerEventId}`);
    },
  });
}

export function createCanonicalMockFintocPaymentRepository() {
  return createMockFintocPaymentRepository(getCanonicalFintocPaymentStorage());
}
